version: "3.7"

services:
  oraclelinux:
    container_name: oracle-server-db
    image: gvenzl/oracle-xe:latest
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "Oracle_123"
    volumes:
      - ./oracle-data:/opt/oracle/oradata
      - ./oracle-backup:/opt/oracle/backup