CREATE TABLE STATUS_ATIVO (
    COD_STATUS INT PRIMARY KEY,
    DESCRICAO VARCHAR(1)
);

CREATE TABLE STATUS_CHAMADO (
    STATUS_CHAMADO INT PRIMARY KEY,
    STATUS CHAR(1) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE CATEGORIA (
    COD_CATEGORIA INT PRIMARY KEY,
    STATUS INT NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    DATA_INICIO DATE NOT NULL,
    DATA_TERMINO DATE,
    FOREIGN KEY (STATUS) REFERENCES STATUS_ATIVO(COD_STATUS)
);

CREATE TABLE PRODUTO (
    COD_PRODUTO INT PRIMARY KEY,
    STATUS INT,
    CATEGORIA INT,
    DESCRICAO_NORMAL VARCHAR(255) NOT NULL UNIQUE,
    DESCRICAO_COMPLETA VARCHAR(255) NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    CODIGO_DE_BARRAS VARCHAR(255),
    FOREIGN KEY (STATUS) REFERENCES STATUS_ATIVO(COD_STATUS),
    FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA)
);



CREATE TABLE VIDEO (
    COD_VIDEO INT PRIMARY KEY,
    STATUS INT,
    DATA_VISUALIZACAO TIMESTAMP NOT NULL,
    CONTADOR_DE_VISUALIZACOES INT,
    CLIENTE INT,
    PRODUTO INT NOT NULL,
    CLASSIFICACAO_VIDEO INT,
    FOREIGN KEY (STATUS) REFERENCES STATUS_ATIVO(COD_STATUS),
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
    FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
    FOREIGN KEY (CLASSIFICACAO_VIDEO) REFERENCES CLASSIFICACAO_VIDEO(CLASSIFICACAO_VIDEO)
);

CREATE TABLE CLASSIFICACAO_VIDEO (
    CLASSIFICACAO_VIDEO INT PRIMARY KEY,
    DESCRICAO_CLASSIFICACAO VARCHAR(255) NOT NULL
);

CREATE TABLE CHAMADO (
    COD_CHAMADO INT PRIMARY KEY,
    CLIENTE INT NOT NULL,
    FUNCIONARIO INT,
    PRODUTO INT NOT NULL,
    DATA_ABERTURA_CHAMADO TIMESTAMP NOT NULL,
    DATA_FECHAMENTO_CHAMADO TIMESTAMP,
    DATA_ATENDIMENTO TIMESTAMP,
    STATUS_CHAMADO INT,
    TEMPO_ATENDIMENTO TIME,
    SATISFACAO INT,
    TIPO INT,
    TEXTO_CHAMADO VARCHAR(4000),
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
    FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO),
    FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
    FOREIGN KEY (STATUS_CHAMADO) REFERENCES STATUS_CHAMADO(STATUS_CHAMADO)


CREATE TABLE DUVIDA_CHAMADO (
    COD_CHAMADO INT PRIMARY KEY,
    DUVIDA VARCHAR(4000),
    FOREIGN KEY (COD_CHAMADO) REFERENCES CHAMADO(COD_CHAMADO)
);

CREATE TABLE SUGESTAO_CHAMADO (
    COD_CHAMADO INT PRIMARY KEY,
    SUGESTAO VARCHAR(4000),
    FOREIGN KEY (COD_CHAMADO) REFERENCES CHAMADO(COD_CHAMADO)
);

CREATE TABLE FUNCIONARIO (
    COD_FUNCIONARIO INT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL,
    CARGO VARCHAR(255) NOT NULL,
    NOME_DEPARTAMENTO VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTE (
    COD_CLIENTE INT PRIMARY KEY,
    QUANTIDADE_ESTRELAS INT,
    STATUS_ATIVO INT NOT NULL,
    NUMERO_TELEFONE VARCHAR(255),
    LOGIN VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    E_LOGADO CHAR(1) NOT NULL,
    NOME_CLIENTE VARCHAR(255),
    FOREIGN KEY (STATUS_ATIVO) REFERENCES STATUS_ATIVO(COD_STATUS)
);

CREATE TABLE PESSOA_FISICA_CLIENTE (
    COD_CLIENTE INT PRIMARY KEY,
    CPF VARCHAR(255) NOT NULL UNIQUE,
    DATA_NASC DATE NOT NULL,
    SEXO_BIOLOGICO CHAR(1) NOT NULL,
    GENERO VARCHAR(255),
    FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);

CREATE TABLE PESSOA_JURIDICA_CLIENTE (
    COD_CLIENTE INT PRIMARY KEY,
    DATA_FUNDACAO TIMESTAMP,
    CNPJ VARCHAR(255),
    IE VARCHAR(255),
    FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);

CREATE TABLE LEAD (
    COD_PRODUTO_COMERCIALIZADO INT PRIMARY KEY,
    PRODUTO INT,
    VIDEO INT,
    CLIENTE INT,
    FUNCIONARIO INT,
    TAXA_CONVERSAO_CLIENTE INT NOT NULL,
    TAXA_CONVERSAO_PRODUTO INT NOT NULL,
    FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
    FOREIGN KEY (VIDEO) REFERENCES VIDEO(COD_VIDEO),
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
    FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO)
);

CREATE TABLE VENDA (
    COD_VENDA INT PRIMARY KEY,
    CLIENTE INT,
    PRODUTO INT,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
    FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);
